name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtk-3-dev

    - name: Run make
      run: make

    - name: Run make install
      run: make install

    - name: Run make format
      run: make format